import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryProvider } from "./provider/ReactQueryProvider";
import { Colors } from "./utils/Colors";
import GoogleAnalytics from "@bradgarropy/next-google-analytics";
import { Navbar } from "@/components/Navbar";
import NextAuthProvider from "@/app/provider/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Puntospoint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en" style={{ backgroundColor: Colors.bg_color_primary }}>
        <GoogleAnalytics measurementId="G-95E3RZE0J0" />
        <body className={inter.className}>
          <NextAuthProvider>
            {children}
          </NextAuthProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
