import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryProvider } from "./ReactQueryProvider";
import { Colors } from "./utils/Colors";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Puntospoint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en" style={{backgroundColor: Colors.bg_color_primary}}>
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
